<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>

        <TailwindVersion>v4.1.18</TailwindVersion>
        <TailwindWatch>true</TailwindWatch>
        <TailwindInputCssFile>Tailwind/style.tw.css</TailwindInputCssFile>
        <TailwindOutputCssFile>public/style.css</TailwindOutputCssFile>
        <TailwindMinifyOnPublish>false</TailwindMinifyOnPublish>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="public/**/*">
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Tailwind\style.tw.css" />
    </ItemGroup>
    
    <Target Name="UsePublicNotWwwroot" AfterTargets="Publish">
        <RemoveDir Directories="$(PublishDir)/wwwroot" />
    </Target>

    <!-- this is nixos' fault -->
    <Target Name="UseSystemTailwindcssIfPresent"
            AfterTargets="TailwindSetupExecutable"
            Condition="Exists('/etc/NIXOS')">
        <Exec Command="which tailwindcss" ConsoleToMsBuild="true">
            <Output TaskParameter="ConsoleOutput" PropertyName="which_tailwindcss" />
        </Exec>
        <Exec Command="rm $(_TailwindExecutablePath)" />
        <Exec Command="ln -s $(which_tailwindcss) $(_TailwindExecutablePath)" />
    </Target>
    
    <ItemGroup>
      <PackageReference Include="FluentResults" Version="4.0.0" />
      <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
      <PackageReference Include="Markdig" Version="1.3.2" />
      <PackageReference Include="NUglify" Version="1.21.17" />
      <PackageReference Include="Tailwind.Hosting" Version="1.2.4" />
      <PackageReference Include="Tailwind.Hosting.Build" Version="1.2.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="ThrottleDebounce" Version="2.0.2" />
    </ItemGroup>

</Project>
